### PR TITLE
Tony Nguyen - Added my standing and regular image

### PR DESCRIPTION
**Pull request by NguyenTony727**
images

### CODE REVIEW

**Comment by SanathVenkatachalam** [comment]
my goat jonkler

**Review by ANagarur — APPROVED** [review]

**Comment by NguyenTony727** [comment]
![Jonkler] (https://tenor.com/jw6BWvzqgtJ.gif)

**Comment by NguyenTony727** [comment]
Alt text

**Comment by MaddikeraShailesh** [comment]
this is so cool

**Pull request merged**
